// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://nxorytadxqfncsbevfzr.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Im54b3J5dGFkeHFmbmNzYmV2ZnpyIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTMyNTgwODUsImV4cCI6MjA2ODgzNDA4NX0.V-EShU0Jw0sQ_wrWMVxIiNDiaOu4F3mBV6kX5hg3qH8";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});